### PR TITLE
Adding Support for CloudWatch Extended Statistics

### LINKED ISSUE #13: Please add support for Cloudwatch extended statistics
Please add support for `aws_extended_statistics` as done in https://github.com/prometheus/cloudwatch_exporter/pull/57

We're trying to get the [`TargetResponseTime` metrics as described in the docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html) and as noted:

> Statistics: The most useful statistics are Average and pNN.NN (percentiles).

So I tried:

```
      - aws_namespace: 'AWS/ApplicationELB'
        aws_metric_name: 'TargetResponseTime'
        aws_statistics: ['p90', 'p95', 'p99']
        aws_dimensions: ['TargetGroup', 'LoadBalancer']
        aws_dimensions_select_regex:
          TargetGroup: .*
          LoadBalancer: app/production-.*
```
and just `aws_statistics: ['p95']`:
```
      - aws_namespace: 'AWS/ApplicationELB'
        aws_metric_name: 'TargetResponseTime'
        aws_statistics: ['p95']
        aws_dimensions: ['TargetGroup', 'LoadBalancer']
        aws_dimensions_select_regex:
          TargetGroup: .*
          LoadBalancer: app/production-.*
```
But both returns this error in the logs:

```
Oct 09 04:32:14 REDACTED cloudwatch_exporter[13161]: InvalidParameterValue: The parameter Statistics.member.1 must be a value in the set [ Minimum, Maximum, Average, SampleCount, Sum ].
Oct 09 04:32:14 REDACTED cloudwatch_exporter[13161]:         status code: 400, request id: REDACTED
```

### PR DESCRIPTION
**Pull request by jonathansm1th**
Adding Support for CloudWatch Extended Statistics.

This closes #13 .

### CODE REVIEW

**Comment by jonathansm1th** [comment]
Still relevant!

**Comment by samuelb** [comment]
It is!

**Comment by a-teisseire** [comment]
Tested and approved!

**Pull request merged**
